### ISSUE TITLE
Binson parser reports no error and returns NULL pointer

### ISSUE THREAD

**Issue by sijohans** [assaabloy-ppi/binson-c-light#3]
Given a fault input data, the binson_parser and binson_parser_get_bytes_bbuf will indicate no fault. But the pointer to the parsed bytes is set to NULL.

```c
#include <stdio.h>
#include "binson_light.h"
#include "assert.h"
#include <stdlib.h>

int main(void)
{
    uint8_t buf[] = {0x40, 0x14, 0x01, 0x65, 0x10, 0x20, 0x85, 0x20 };
    binson_parser p;
    binson_parser_init(
        &p,
        buf,
        sizeof(buf));

    binson_parser_field(&p, "e");
    bbuf *binson_bytes = binson_parser_get_bytes_bbuf(&p);

    assert(p.error_flags == BINSON_ID_OK);
    
    assert(binson_bytes->bptr != NULL);

}
```

which gives this output:
```
$ gcc main.c binson_light.c
$ ./a.out 
a.out: binson_bug.c:20: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
```

Later, if assuming that everything is OK, a memcpy from binson_bytes->bptr could result in segmentation fault.

**Comment by sijohans** [comment]
Using the following program:
```c
#include <stdio.h>
#include "binson_light.h"
#include "assert.h"
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

int main(void)
{
    uint8_t buf[2048];
    read(0, buf, sizeof(buf));

    binson_parser p;
    binson_parser_init(
        &p,
        buf,
        sizeof(buf));

    binson_parser_field(&p, "e");
    if (p.error_flags != BINSON_ID_OK) {
        return 0;
    }

    bbuf *binson_bytes = binson_parser_get_bytes_bbuf(&p);
    if (p.error_flags != BINSON_ID_OK) {
        return 0;
    }

    assert(binson_bytes->bptr != NULL);

}
```

Also this input data result in assertion error:
```
$ gcc main.c binson_light.c -o binson_test.o
$ echo -n -e '\x40\x14\x01\x65\x12\x20\x85\x20' | ./binson_test.o
binson_test.o: binson_afl.c:29: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
$ echo -n -e '\x40\x14\x01\x65\x46\x20\x85\x20' | ./binson_test.o
binson_test.o: binson_afl.c:29: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
$ echo -n -e '\x40\x14\x01\x65\x13\x20\x85\x20' | ./binson_test.o
binson_test.o: binson_afl.c:29: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
$ echo -n -e '\x40\x14\x01\x65\x10\x20\x85\x20' | ./binson_test.o
binson_test.o: binson_afl.c:29: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
$ echo -n -e '\x40\x14\x01\x65\x11\x20\x85\x20' | ./binson_test.o
binson_test.o: binson_afl.c:29: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
$ echo -n -e '\x40\x14\xfd\x65\x18\x20\x85\x20' | ./binson_test.o
binson_test.o: binson_afl.c:29: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
```

**Comment by ppmag** [comment]
Thank you for detailed reproduction instructions.
Fixed in  8c79693

**Comment by sijohans** [comment]
Hello again, i found two cases where this is still a problem. Given this program:
```c
#include <stdio.h>
#include "../../pot-c/binson_light.h"
#include "assert.h"
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

int main(void)
{

    uint8_t buf[2048];
    read(0, buf, sizeof(buf));

    binson_parser p;
    binson_parser_init(
        &p,
        buf,
        sizeof(buf));

    /* We are expecting a byte array in the field "e" */
    binson_parser_field(&p, "e");
    if (p.error_flags != BINSON_ID_OK) {
        return 0;
    }

    if (binson_parser_get_type(&p) != BINSON_ID_ARRAY)
    {
        return 0;
    }

    bbuf *binson_bytes = binson_parser_get_bytes_bbuf(&p);
    if (p.error_flags != BINSON_ID_OK) {
        return 0;
    }

    assert(binson_bytes->bptr != NULL);

}
```

we will with some input data fail in the assert:
```
$ gcc main.c binson_light.c -o binson_test.o
$ echo -n -e '\x40\x14\x01\x65\x42\x20\x85\x20' | ./binson_test.o
binson.out: fuzz_tests/binson/binson.c:36: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
$ echo -n -e '\x40\x14\x01\x00\x42\x57\x14\x01\x65\x42\x43\x40\x0b\x00\x42\x40\x14\x01\x00\x42\x43\x40\x14\x01\x00\x42\x40' | ./binson_test.o
binson.out: fuzz_tests/binson/binson.c:36: main: Assertion `binson_bytes->bptr != NULL' failed.
Aborted
```

Is this the correct way to use the Binson API?

**Comment by ppmag** [comment]
Hi, it's due to "compatibility mode".
While testing pls
comment line
https://github.com/assaabloy-ppi/binson-c-light/blob/master/binson_light.c#L705
and uncomment next one.

**Comment by sijohans** [comment]
Great, i also see that in the test case, the line:
```c
if (binson_parser_get_type(&p) != BINSON_ID_ARRAY)
```

should have been:
```c
if (binson_parser_get_type(&p) != BINSON_ID_BYTES)
```

**Comment by franslundberg** [comment]
Simon, Alex, nice to see good bug reports and fixes taking binson lib
forward. Have a nice weekend!
